{
    'name': 'Inova Technology - Report Layouts',
    'version': '19.0.1.0.0',
    'category': 'Sales',
    'summary': 'Custom report layouts for Inova Technology: Proforma Invoice, Tax Invoice enhancements, and Statement of Accounts',
    'author': 'Inova Technology',
    'website': 'https://inova.technology',
    'maintainer': 'Inova Technology',
    'license': 'LGPL-3',
    'depends': ['sale', 'account', 'it_contacts'],
    'data': [
        'security/ir.model.access.csv',
        'data/account_payment_method_data.xml',
        'report/proforma_invoice_report.xml',
        'report/tax_invoice_enhancements.xml',
        'report/statement_of_accounts_report.xml',
        'views/sale_order_views.xml',
        'views/account_move_views.xml',
        'views/account_cheque_views.xml',
        'views/statement_of_accounts_wizard_views.xml',
        'views/res_partner_views.xml',
    ],
    'installable': True,
    'application': False,
}
